-- Phase C: registration SMS domain events + confirmation template purpose.

-- AlterEnum DomainEventType
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_COMPLETED';
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_PAYMENT_SUCCESS';
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_PAYMENT_PENDING';
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_APPROVED';
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_REJECTED';
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_NEEDS_CORRECTION';
ALTER TYPE "DomainEventType" ADD VALUE 'DISCOUNT_EXPIRING';
ALTER TYPE "DomainEventType" ADD VALUE 'REGISTRATION_DEADLINE_REMINDER';

-- AlterEnum SmsTemplatePurpose
ALTER TYPE "SmsTemplatePurpose" ADD VALUE 'REGISTRATION_CONFIRMATION';
